### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by jpommerening** [jpommerening/release-station#1]
Stuff to do before "releasing milestone 1".
Things that warrant a separate issue will be filed as such and linked below.
## Non-functional
- [ ] add proper `README.md` file explaining installation and integration steps
- [ ] move repository to @LaxarJS
- [x] add `gh-pages` branch for GitHub hosting
- [x] upgrade to Laxar 1.1.0
## Common to all pages
- [x] rename headline "ReleaseStation" -> "ReleaseStation _for GitHub_" (15d7b9cf)
- [x] scale down avatar, add name (a999fa5e)
- [x] scale down navigation bar (a999fa5e)
- [x] make queried repositories a "runtime configuration" instead of a page/widget config  
    (i.e. ask the user to select repositories they want to look at; store settings in `localStorage` or smth.)
## Grid
- [x] include scope (period under consideration, e.g. "last month") in headline "Activity Overview" (2d978af)
- [x] resize details to match height of the chart (maybe find a better layout altogether (abbe518)
- [x] show all repositories, sorted by activity (instead of top 12) (12eb9b9)
- [x] #3: add filter input (filter by repository name)
## Calendar
- [x] don't include issues in event data (1ebb04e8)
- [x] #2: add month selector (top right corner)
- [x] reevaluate color choice (orange/blue)
- [x] highlight days with events (or: reduce emphasis on days without events)
- [x] add spacing around "day of month" (15d7b9cf)
- [x] add a popup/popover to view detailed events (issues, releases) on a specific day
- [x] avoid the need to scroll down on "average sized" displays
  - [x] reduce navigation bar size (see above)
  - [x] reduce whitespace around headlines (a999fa5e)
  - [x] what else?  
     (if I'm not mistaken, the demo header takes 107px, which is huge on my 1280x800 display)
- [x] #3: add filter input (reduce events displayed on the page, for example show only events of repositories containing "widget" in their name)
## Timeline
- [x] rename headline / page "Release Timeline" -> "Release _History_" (6f8d586f)
- [ ] show all repositories with one repository per "well", separate major versions with (dashed) lines
- [x] link changelogs to version entries
- [ ] link to "last changes" (aka "coming up", changes to be released in the next version) per major version
- [ ] #3: add filter input (filter displayed repositories and maybe versions)

/cc @mkemmann

**Comment by jpommerening** [comment]
@mkemmann: Preview available at https://jpommerening.github.io/release-station
